version: "3.0"
services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command:
      #      - 加入参数，设置 binlog 和主节点
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
      - --server-id=1
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #      设置初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      #      注意这里我映射为了 13316 端口
      - "13316:3306"

  redis:
    image: 'bitnami/redis:7.2'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '16379:6379'

  etcd:
    image: 'bitnami/etcd:3.5.9'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
#      所以你要用 12379 端口来连接 etcd
      - 12379:2379

  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      #      - 将本地的 prometheus 文件映射到容器内的配置文件
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      #      - 访问数据的端口
      - 19090:9090

  grafana:
    image: grafana/grafana-enterprise:10.2.0
    ports:
      - 3000:3000

  zipkin:
    #    用的是不支持 Kafka 之类的简化版本
    image: openzipkin/zipkin-slim:2.24
    ports:
      - '9411:9411'